services:
  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
      target: development
    restart: unless-stopped
    command: pnpm run start:dev gateway
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules